@url = http://localhost:3000/api

### API AUTORES
# Registrarse/Crear autor
POST {{url}}/autores/registro
Content-Type: application/json
{
  "nombre": "test",
  "email": "test@gmail.com",
  "password": "pass"
}

###
# Obtener todos los autores
GET {{url}}/autores

###
# Obtener todos los posts de un autor específico.
GET {{url}}/posts/autores/1

###
# Obtener un autor por ID
GET {{url}}/autores/1

###
# Obtener todos los autores
GET {{url}}/autores


###
# Obtener todos los posts
GET {{url}}/posts

###
# Crear un nuevo post
POST {{url}}/posts/new
Content-Type: application/json
{
  "titulo": "Titulo del post",
  "descripcion": "Descripcion del post",
  "fecha_creacion": "{{$datetime 'YYYY-MM-DD HH:mm:ss'}}",
  "categoria": "Tecnología",
  "autor_id": 1
}

